# Copyright (C) 2016-2017 DeathCore <http://www.noffearrdeathproject.org/>
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

sudo: required
dist: trusty

language: cpp
compiler:
  - clang

git:
  depth: 1

before_install:
  - sudo apt-get -qq install build-essential libtool make cmake cmake-data openssl
  - sudo apt-get -qq install libssl-dev libmysqlclient-dev libmysql++-dev libreadline6-dev zlib1g-dev libbz2-dev
  - sudo apt-get -qq install libboost1.55-dev libboost-thread1.55-dev libboost-filesystem1.55-dev libboost-system1.55-dev libboost-program-options1.55-dev libboost-iostreams1.55-dev libboost-regex1.55-dev
  - git config user.email "travis@build.bot" && git config user.name "Travis CI"
  - git tag -a -m "Travis build" init

install:
  - mysql -uroot -e 'create database test_mysql;'
  - mkdir bin
  - cd bin
  - cmake ../ -DWITH_WARNINGS=1 -DWITH_COREDEBUG=0 -DUSE_COREPCH=1 -DUSE_SCRIPTPCH=1 -DTOOLS=1 -DSCRIPTS="dynamic" -DSERVERS=1 -DNOJEM=1 -DWITH_DYNAMIC_LINKING=1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS="-Werror" -DCMAKE_CXX_FLAGS="-Werror" -DCMAKE_INSTALL_PREFIX=check_install
  - cd ..
  - chmod +x contrib/check_updates.sh

script:
  - $CXX --version
  - mysql -uroot < sql/create/create_mysql.sql
  - mysql -udeathcore -pdeathcore auth < sql/base/auth_database.sql
  - cat sql/updates/auth/master/*_auth.sql -h 127.0.0.1 | mysql -u deathcore -pdeathcore world -h 127.0.0.1
  - mysql -udeathcore -pdeathcore characters < sql/base/characters_database.sql
  - cat sql/updates/characters/master/*_characters.sql -h 127.0.0.1 | mysql -u deathcore -pdeathcore world -h 127.0.0.1
  - mysql -udeathcore -pdeathcore world < sql/base/dev/world_database.sql
  - mysql -udeathcore -pdeathcore hotfixes < sql/base/dev/hotfixes_database.sql
  - cat sql/updates/world/master/*_world.sql | mysql -udeathcore -pdeathcore world
  - cat sql/updates/hotfixes/master/*_hotfixes.sql | mysql -udeathcore -pdeathcore hotfixes
  - mysql -uroot < sql/create/drop_mysql.sql
  - cd bin
  - make -j 8 -k && make install
  - cd check_install/bin
  - ./bnetserver --version
  - ./worldserver --version
